# --- Colors / Theme ---
[window]
startup_mode = 'Maximized'

[colors.bright]
black = '#686868'
blue = '#6871ff'
cyan = '#60fdff'
green = '#5ffa68'
magenta = '#ff77ff'
red = '#ff6e67'
white = '#ffffff'
yellow = '#fffc67'

[colors.cursor]
cursor = '#c7c7c7'
text = '#8c8c8c'

[colors.normal]
black = '#000000'
blue = '#0225c7'
cyan = '#00c5c7'
green = '#00c200'
magenta = '#ca30c7'
red = '#c91b00'
white = '#c7c7c7'
yellow = '#c7c400'

[colors.primary]
background = '#000000'
foreground = '#c7c7c7'

[colors.selection]
background = '#c1deff'
text = '#000000'

# --- Font Settings ---
[font.normal]
family = "UbuntuSansMono NFM"
style = "Regular"

[font]
size = 18

# --- Key Bindings ---
# Disable Ctrl+Enter
[[keyboard.bindings]]
key = "Enter"
mods = "Control"
action = "None"

